name: distwar_colmap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.1
  - plyfile=0.8.1
  - python=3.11.6
  - pip=22.3.1
  - pytorch=2.1.1
  - torchaudio=2.1.1
  - torchvision=0.16.1
  - tqdm
